### ISSUE TITLE
Module name validation

### ISSUE THREAD

**Issue by vietj** [dmlloyd/module-info#91]
Module name present in YML descriptor should be validated, somehow I made a mistake and typed  `- module: io.netty.codec.http;` in a descriptor and the created a module with such non sense name and the JVM tried to load it

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module io.netty.codec.http; not found, required by io.netty.handler.ssl.ocsp
```

**Comment by dmlloyd** [comment]
Module name validity is fluid where the JVM is concerned. The language has certain restrictions on what can be in a module name, however the JDK and JVM do not have any such restrictions. So, it is more of a feature than a bug.

It might be useful to restrict the syntax to the Java language rules by default but allow non-conforming names if a switch is flipped.

This can be compared to the situation with module versions, which have a very restrictive syntax if you make them with the API. Many, if not most, Maven projects violate these rules though and in practice it's not a problem.

**Comment by vietj** [comment]
@dmlloyd it makes sense to me

**Comment by vietj** [comment]
thank you @dmlloyd
